import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from './providers/QueryProvider';
import Header from '../components/Header';
import React from 'react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" style={{ backgroundColor: '#ffffff' }}>
        <Header />
        <QueryProvider>
          <main className="flex-1 w-full">
            <div className="container mx-auto px-6 py-1 max-w-9xl">
              <div className="bg-white rounded-lg p-0 h-[100vh] max-h-[90vh] overflow-y-auto">
                {children}
              </div>
            </div>
          </main>
        </QueryProvider>
      </body>
    </html>
  );
}
