import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from './providers/QueryProvider';
import Sidebar from '../components/Sidebar';
import SectionHeader from '../components/SectionHeader';
import React from 'react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-screen antialiased`}
    >
      <body className="h-screen flex flex-row overflow-hidden" style={{ backgroundColor: '#ffffff' }}>
        <Sidebar />
        <QueryProvider>
          <main className="flex-1 w-full h-full flex flex-col overflow-hidden">
            <SectionHeader />
            <div className="flex-1 w-full overflow-auto">
              {children}
            </div>
          </main>
        </QueryProvider>
      </body>
    </html>
  );
}
